### ISSUE TITLE
Django 4.x: import of gettext failing

### ISSUE THREAD

**Issue by frlan** [thornomad/django-hitcount#117]
When using Django 4 the gettext import is failing:

```
Traceback (most recent call last):
  File "/home/frlan/myproject/manage.py", line 21, in <module>
    main()
  File "/home/frlan/myproject/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/frlan/myproject/lib/python3.9/site-packages/django/core/management/__init__.py", line 425, in execute_from_command_line
    utility.execute()
  File "/home/frlan/myproject/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute
    django.setup()
  File "/home/frlan/myproject/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/frlan/myproject/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/frlan/myproject/lib/python3.9/site-packages/django/apps/config.py", line 300, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/frlan/myproject/lib/python3.9/site-packages/hitcount/models.py", line 12, in <module>
    from django.utils.translation import ugettext_lazy as _
ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation' (/home/frlan/myproject/lib/python3.9/site-packages/django/utils/translation/__init__.py)

```

It appears that ugettext_lazy was removed with 4.0 release -- from [announcemnet](https://docs.djangoproject.com/en/dev/internals/deprecation/):

> django.utils.translation.ugettext(), ugettext_lazy(), ugettext_noop(), ungettext(), and ungettext_lazy() will be removed.

**Comment by Razilator** [comment]
I'd like the author to fix it. I fixed it myself, but unfortunately I can't on the server, since this is a big problem with docker containers. We are waiting for the update and it will be possible to upgrade to Django 4.0

**Comment by Gako358** [comment]
I would like to know how you manage to fix this, i could not.

**Comment by bashu** [comment]
should be fixed in 267bfef2d48eef7e1ad783df6cef7d06ce60b236

**Comment by Razilator** [comment]
great, waiting!

**Comment by bashu** [comment]
try django-hitcount == 1.3.5
